SELECT
    YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , GENDER
    , COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM
    ONLINE_SALE AS O
    LEFT JOIN
    USER_INFO AS U
    ON O.USER_ID = U.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
