/*
FOOD_PRODUCT, FOOD_ORDER 생산일자가 2022년 5월인 식품
식품 ID, 식품 이름, 총매출을 조회하는 SQL문
이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 
총매출이 같다면 식품 ID를 기준으로 오름차순 정렬해주세요.
*/

SELECT FP.PRODUCT_ID AS PRODUCT_ID
       , FP.PRODUCT_NAME AS PRODUCT_NAME
       , (SUM(FO.AMOUNT) * FP.PRICE) AS TOTAL_SALES
  FROM FOOD_PRODUCT AS FP
       LEFT JOIN FOOD_ORDER AS FO
       ON FP.PRODUCT_ID = FO.PRODUCT_ID
 WHERE LEFT(FO.PRODUCE_DATE, 7) = '2022-05'
 GROUP BY FP.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID